### PR TITLE
#4 Update readme with usage information

### PR DESCRIPTION
**Pull request by m4ver1k**

### CODE REVIEW

**Review by komish — CHANGES_REQUESTED** [review]
@m4ver1k This looks great! Thanks so much for contributing. 

Can you change the wording around the configuration file to reference `os.UserConfigDir()` ([docs](https://golang.org/pkg/os/#UserConfigDir)) to determine where the config should be placed? This doesn't directly translate to `$HOME` for all target OSes.

EDIT: don't concern yourself with the tests failing, I'm working on fixing those.

**Comment by m4ver1k** [comment]
Sure I will update that

**Comment by m4ver1k** [comment]
Hi @komish I have incorporated the PR with feedbacks

**Review by komish — APPROVED** [review]
@m4ver1k That will work! Thanks again!

**Pull request merged**
